### ISSUE TITLE
api: partial validation at commit

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-records#162] opened 2016-11-18 14:57 UTC
**Problem:**
Partial validation is already possible [when records are created](https://github.com/inveniosoftware/invenio-records/blob/091fca39595339cd4ee35ad111f7be17aa9c10cd/invenio_records/api.py#L140). However it is not possible when modifying a record and [calling `commit`](https://github.com/inveniosoftware/invenio-records/blob/091fca39595339cd4ee35ad111f7be17aa9c10cd/invenio_records/api.py#L266).

**Suggested solution:**
Allow to pass a validator to the `validate` function in `commit`.

Relates to #140

**Comment by jirikuncar** [comment] 2016-11-18 15:12
IMHO it's duplicate of https://github.com/inveniosoftware/invenio-records/issues/146

**Comment by nharraud** [comment] 2016-11-18 15:22
@jirikuncar But #146 is closed. I thought that we reopened tickets mainly for bugs when they reappeared.

**Comment by jirikuncar** [comment] 2016-11-19 09:14
It would be easier for many developers to get context if you reopen the old ticket with an use-case that was forgotten or at least reference #146 together with #140.

**Closed** 2016-12-05 10:09 UTC
Labels: Size: easy, Status: in review, Type: enhancement
